queue_rules:
  - name: automerge
    conditions:
      - check-success=Qiskit.qiskit-machine-learning

pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - check-success=Qiskit.qiskit-machine-learning
      - "#approved-reviews-by>=1"
      - label=automerge
      - label!=on hold
    actions:
      queue:
        name: automerge
        method: squash
  - name: backport
    conditions:
      - label=stable backport potential
    actions:
      backport:
        branches:
          - stable/0.2
