queue_rules:
  - name: automerge
    conditions:
      - check-success=Deprecation_Messages_and_Coverage (3.8)

pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - check-success=Deprecation_Messages_and_Coverage (3.8)
      - "#approved-reviews-by>=1"
      - label=automerge
      - label!=on hold
    actions:
      queue:
        name: automerge
        method: squash
  - name: backport
    conditions:
      - label=stable backport potential
    actions:
      backport:
        branches:
          - stable/0.6
