pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - "#approved-reviews-by>=1"
      - label=automerge
      - label!=on hold
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: backport
    conditions:
      - label=stable backport potential
    actions:
      backport:
        branches:
          - stable/0.1
