# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Qiskit Machine Learning Main Dependencies'
description: 'Installs Python dependencies from Main'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies from Main
      env:
        DISABLE_CONAN: 1
      run: |
        pip install git+https://github.com/Qiskit/qiskit-terra
        sudo apt-get -y install nlohmann-json3-dev
        sudo apt-get -y install libspdlog-dev
        sudo apt-get -y install libmuparserx-dev
        pip install git+https://github.com/Qiskit/qiskit-aer
      shell: bash
