# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Qiskit Machine Learning Main Dependencies'
description: 'Installs Python dependencies from Main'
inputs:
  os:
    description: 'OS'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Dependencies from Main
      run: |
        pip install git+https://github.com/Qiskit/qiskit-terra
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
          export DISABLE_CONAN=1
          sudo apt-get -y install nlohmann-json3-dev
          sudo apt-get -y install libspdlog-dev
          sudo apt-get -y install libmuparserx-dev
        fi
        if [ "${{ inputs.os }}" == "windows-2019" ]; then
          git clone https://github.com/Qiskit/qiskit-aer.git /tmp/qiskit-aer
          pushd /tmp/qiskit-aer
          python setup.py bdist_wheel -- -G 'Visual Studio 16 2019'
          pip install --find-links=dist qiskit-aer
          popd
        else
          pip install git+https://github.com/Qiskit/qiskit-aer
        fi
      shell: bash
