# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Run Unit Tests'
description: 'Run Unit Tests'
inputs:
  event-name:
    description: 'Actions event'
    required: true
  run-slow:
    description: 'Run slow tests or not'
    required: true
  python-version:
    description: 'Python version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Unit Tests
      env:
        PYTHONWARNINGS: default
      run: |
        # run slow tests only on scheduled event or if input flag is set
        if [ "${{ inputs.event-name }}" == "schedule" ] || [ "${{ inputs.run-slow }}" == "true" ]; then
          export QISKIT_TESTS="run_slow"
        fi
        if [ "${{ inputs.python-version }}" == "3.7" ]; then
          export PYTHON="coverage3 run --source qiskit_machine_learning --parallel-mode"
        fi
        stestr --test-path test run 2> >(tee /dev/stderr out.txt > /dev/null)
      shell: bash