# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Machine Learning Unit Tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    # run every day at 1AM
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  Checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Print Concurrency Group
        env:
          CONCURRENCY_GROUP: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}
        run: |
          echo -e "\033[31;1;4mConcurrency Group\033[0m"
          echo -e "$CONCURRENCY_GROUP\n"
        shell: bash
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-libraries
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-main-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-machine-learning
      - name: Install Dependencies
        run: |
          pip install jupyter sphinx_rtd_theme 'matplotlib<3.3.0' qiskit-terra[visualization] 'torchvision<0.10.0'
          sudo apt-get -y install pandoc graphviz
          sudo apt-get -y install python3-enchant
          sudo apt-get -y install hunspell-en-us
          pip install pyenchant
        shell: bash
      - run:  pip check
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make copyright
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make spell
        if: ${{ !cancelled() }}
        shell: bash
      - run:  make style
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run make html
        run:  |
          make clean_sphinx
          make html SPHINXOPTS=-W
          cd docs/_build/html
          mkdir artifacts
          tar -zcvf artifacts/documentation.tar.gz --exclude=./artifacts .
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/_build/html/artifacts/documentation.tar.gz
        if: ${{ !cancelled() }}
      - run:  make doctest
        if: ${{ !cancelled() }}
        shell: bash
  MachineLearning:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-libraries
      - uses: ./.github/actions/install-main-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-machine-learning
      - run: make lint
        shell: bash
      - run: make mypy
        if: ${{ !cancelled() }}
        shell: bash
      - name: Run make lint latest version
        run: |
          pip install -U pylint
          make lint
        shell: bash
      - name: Machine Learning Unit Tests under Python ${{ matrix.python-version }}
        uses: ./.github/actions/run-tests
        with:
          event-name: ${{ github.event_name }}
          run-slow: ${{ contains(github.event.pull_request.labels.*.name, 'run_slow') }}
          python-version: ${{ matrix.python-version }}
        if: ${{ !cancelled() }}
      - name: Deprecation Messages
        run: |
          mkdir ./m${{ matrix.python-version }}
          python tools/extract_deprecation.py -file out.txt -output ./m${{ matrix.python-version }}/ml.dep
        shell: bash
      - name: Coverage combine
        run: |
          coverage3 combine
          mv .coverage ./m${{ matrix.python-version }}/ml.dat
        if: ${{ matrix.python-version == 3.7 }}
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: ml${{ matrix.python-version }}
          path: ./m${{ matrix.python-version }}/*
      - name: Machine Learning Unit Tests without torch/sparse under Python ${{ matrix.python-version }}
        env:
          PYTHONWARNINGS: default
        run: |
          pip uninstall -y torch sparse
          if [ "${{ github.event_name }}" == "schedule" ] || [ "${{ contains(github.event.pull_request.labels.*.name, 'run_slow') }}" == "true" ]; then
              export QISKIT_TESTS="run_slow"
          fi
          stestr --test-path test run
        if: ${{ !cancelled() }}
        shell: bash
  Tutorials:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-libraries
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-main-dependencies
        if: ${{ !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
      - uses: ./.github/actions/install-machine-learning
      - name: Install Dependencies
        run: |
          pip install jupyter sphinx_rtd_theme 'matplotlib<3.3.0' qiskit-terra[visualization] 'torchvision<0.10.0'
          sudo apt-get install -y pandoc graphviz
        shell: bash
      - name: Run Machine Learning Tutorials
        env:
          QISKIT_PARALLEL: False
          QISKIT_DOCS_BUILD_TUTORIALS: 'always'
        run: |
          make html SPHINXOPTS=-W
          cd docs/_build/html
          mkdir artifacts
          tar -zcvf artifacts/tutorials.tar.gz --exclude=./artifacts .
        shell: bash
      - name: Run upload tutorials
        uses: actions/upload-artifact@v2
        with:
          name: tutorials${{ matrix.python-version }}
          path: docs/_build/html/artifacts/tutorials.tar.gz
      - name: Run stable tutorials
        env:
          QISKIT_PARALLEL: False
          QISKIT_DOCS_BUILD_TUTORIALS: 'always'
        run: |
          # clean last sphinx output
          make clean_sphinx
          # get current version
          version=$(pip show qiskit-machine-learning | awk -F. '/^Version:/ { print substr($1,10), $2-1 }' OFS=.)
          # download stable version
          wget https://codeload.github.com/Qiskit/qiskit-machine-learning/zip/stable/$version -O /tmp/repo.zip
          unzip /tmp/repo.zip -d /tmp/
          # copy stable tutorials to main tutorials
          rm -rf docs/tutorials/*
          cp -R /tmp/qiskit-machine-learning-stable-$version/docs/tutorials/* docs/tutorials
          # run tutorials and zip results
          make html SPHINXOPTS=-W
          cd docs/_build/html
          mkdir artifacts
          tar -zcvf artifacts/tutorials.tar.gz --exclude=./artifacts .
        if: ${{ matrix.python-version == 3.8 && !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
        shell: bash
      - name: Run upload stable tutorials
        uses: actions/upload-artifact@v2
        with:
          name: tutorials-stable${{ matrix.python-version }}
          path: docs/_build/html/artifacts/tutorials.tar.gz
        if: ${{ matrix.python-version == 3.8 && !startsWith(github.ref, 'refs/heads/stable') && !startsWith(github.base_ref, 'stable/') }}
  Deprecation_Messages_and_Coverage:
    needs: [MachineLearning]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v2
        with:
          name: ml3.6
          path: /tmp/m36
      - uses: actions/download-artifact@v2
        with:
          name: ml3.7
          path: /tmp/m37
      - uses: actions/download-artifact@v2
        with:
          name: ml3.8
          path: /tmp/m38
      - uses: actions/download-artifact@v2
        with:
          name: ml3.9
          path: /tmp/m39
      - name: Install Dependencies
        run: pip install -U coverage coveralls diff-cover
        shell: bash
      - name: Combined Deprecation Messages
        run: |
          sort -f -u /tmp/m36/ml.dep /tmp/m37/ml.dep /tmp/m38/ml.dep /tmp/m39/ml.dep || true
        shell: bash
      - name: Coverage combine
        run: coverage3 combine /tmp/m37/ml.dat
        shell: bash
      - name: Upload to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
        shell: bash
